; Flavenz WuWa Config - GAMING DeviceProfiles
; Render scale 0.75 + URO anim rate limiting = efek besar di battle fps

[Android_High DeviceProfile]
DeviceScore=6969
CVars=r.imp.SSMbScaleLod0=0.00
CVars=r.imp.SSMbScaleLod1=0.00
CVars=r.Mobile.HighQualityMaterial=1
CVars=r.Android.DisableVulkanSupport=0
CVars=r.Android.VulkanSetting=1
CVars=sg.ResolutionQuality=0.75
CVars=sg.ViewDistanceQuality=2
CVars=sg.AntiAliasingQuality=2
CVars=sg.ShadowQuality=2
CVars=sg.PostProcessQuality=2
CVars=sg.TextureQuality=3
CVars=sg.EffectsQuality=2
CVars=sg.FoliageQuality=1
CVars=sg.ShadingQuality=2
CVars=wp.Runtime.LoadingRangeScale=0.75
CVars=wp.Runtime.PlannedLoadingRangeScale=0.90
CVars=r.KuroFI.InternalResolutionScale=0.5
CVars=a.URO.Enable=1
CVars=a.URO.ForceAnimRate=3
CVars=a.URO.ForceInterpolation=1
