; Flavenz WuWa Config - MAXVISUAL preset
; Target: visual penuh Android_High + Vulkan, WAJIB cooler aktif
; Base: Arglax High-Visual v3.6 (forbidden-cleaned), TAA high, SSR + shadow 8 cascade

[SystemSettings]
dp.Override=Android_High
r.SceneColorFormat=4
r.DefaultBackBufferPixelFormat=0
r.Color.Mid=0.45
r.Mobile.TonemapperFilm=1

FX.AllowAsyncTick=1
FX.AllowCulling=1
FX.AllowFastPathFunctionLibrary=1
FX.AllowGPUParticles=1
FX.AllowGPUSorting=1
FX.BatchAsync=1
FX.BatchAsyncBatchSize=32

r.TemporalAA.HistoryScreenPercentage=100
r.TemporalAA.Quality=2
r.TemporalAA.R11G11B10History=1
r.TemporalAACatmullRom=1
r.TemporalAACurrentFrameWeight=0.2
r.TemporalAAFilterSize=1.0
r.TemporalAAPauseCorrect=1
r.TemporalAASamples=16

r.Shadow.CSMCaching=0
r.Shadow.CacheWPOPrimitives=0
r.Shadow.CachePreshadow=1
r.Shadow.CacheWholeSceneShadows=1
r.Shadow.ConservativeBounds=1
r.Shadow.CSM.MaxCascades=8
r.Shadow.CSM.MaxMobileCascades=8
r.Shadow.CSMDepthBias=8.0
r.Shadow.CSMReceiverBias=0.8
r.Shadow.FilterMethod=0
r.Shadow.MinResolution=512
r.Shadow.PerObject=1
r.Shadow.RadiusThreshold=0.001
r.Shadow.Virtual.Enable=0
r.CapsuleShadows=1
r.CapsuleDirectShadows=1
r.CapsuleIndirectShadows=1
r.DistanceFieldAO=0

r.BloomQuality=4
r.MotionBlurQuality=2
r.DepthOfFieldQuality=2
r.FilmGrain=0
r.SceneColorFringeQuality=1
r.PostProcessAAQuality=6
r.LightShaftQuality=1
r.LightShaftAllowTAA=1
r.LightShaftBlurPasses=3
r.LightShaftNumSamples=12
r.LightShafts=1
r.LensFlareQuality=1
r.Fog=1

r.SSR.Quality=2
r.SSR.HalfResSceneColor=1
r.SSR.Temporal=1
r.SSAO=1
r.AmbientOcclusion=1
r.SSGI.Quality=1
r.SSGI.HalfRes=1

r.Water.SingleLayer.Reflection=1
r.Water.EnableUnderwaterPostProcess=1

r.Kuro.KuroBloomStreak=1
r.StaticMeshLODDistanceScale=0.95

[/Script/Engine.RendererSettings]
r.Android.DisableVulkanSupport=0
r.Android.VulkanSetting=1
r.Mobile.AllowDistanceFieldShadows=1
r.Mobile.HighQualityMaterial=1
