; Flavenz WuWa Config - MAXVISUAL DeviceProfiles
; Full scale 1.0, semua quality max yang didukung mobile

[Android_High DeviceProfile]
DeviceScore=99999
CVars=r.imp.SSMbScaleLod0=0.00
CVars=r.imp.SSMbScaleLod1=0.00
CVars=r.Mobile.HighQualityMaterial=1
CVars=r.Android.DisableVulkanSupport=0
CVars=r.Android.VulkanSetting=1
CVars=sg.ResolutionQuality=1.0
CVars=sg.ViewDistanceQuality=4
CVars=sg.AntiAliasingQuality=4
CVars=sg.ShadowQuality=4
CVars=sg.PostProcessQuality=4
CVars=sg.TextureQuality=4
CVars=sg.EffectsQuality=3
CVars=sg.FoliageQuality=3
CVars=sg.ShadingQuality=4
CVars=wp.Runtime.LoadingRangeScale=0.85
CVars=wp.Runtime.PlannedLoadingRangeScale=1.05
CVars=a.URO.Enable=0
