; Flavenz WuWa Config - POTATO DeviceProfiles
; Render scale 0.65 + URO agresif + streaming hemat

[Android_High DeviceProfile]
DeviceScore=1000
CVars=r.Mobile.HighQualityMaterial=0
CVars=r.Android.DisableVulkanSupport=0
CVars=r.Android.VulkanSetting=1
CVars=sg.ResolutionQuality=0.65
CVars=sg.ViewDistanceQuality=1
CVars=sg.AntiAliasingQuality=1
CVars=sg.ShadowQuality=1
CVars=sg.PostProcessQuality=1
CVars=sg.TextureQuality=2
CVars=sg.EffectsQuality=1
CVars=sg.FoliageQuality=1
CVars=sg.ShadingQuality=1
CVars=wp.Runtime.LoadingRangeScale=0.6
CVars=wp.Runtime.PlannedLoadingRangeScale=0.8
CVars=r.KuroFI.InternalResolutionScale=0.5
CVars=a.URO.Enable=1
CVars=a.URO.ForceAnimRate=4
CVars=a.URO.ForceInterpolation=1
