#!/data/data/com.termux/files/usr/bin/bash

VERSION="V1.0"

R='\033[0;31m'
G='\033[0;32m'
Y='\033[1;33m'
C='\033[0;36m'
M='\033[0;35m'
W='\033[1;37m'
DIM='\033[2m'
BOLD='\033[1m'
BLINK='\033[5m'
NC='\033[0m'

BASE_DIR="${SCRIPT_DIR}"
BACKUP_DIR="$BASE_DIR/backup"
LOG_DIR="$BASE_DIR/logs"
CAP_CACHE="$BACKUP_DIR/cap_cache.txt"

BACKUP_CPU_GOV="$BACKUP_DIR/cpu_gov.txt"
BACKUP_CPU_FREQ="$BACKUP_DIR/cpu_freq.txt"
BACKUP_GPU_GOV="$BACKUP_DIR/gpu_gov.txt"
BACKUP_ZONE_MODES="$BACKUP_DIR/zone_modes.txt"
BACKUP_TRIP_POINTS="$BACKUP_DIR/trip_points.txt"
BACKUP_SCONFIG="$BACKUP_DIR/sconfig.txt"
BACKUP_CORE_CTRL="$BACKUP_DIR/core_ctrl.txt"
BACKUP_SVC_STATES="$BACKUP_DIR/svc_states.txt"
BACKUP_THERMAL_PROP="$BACKUP_DIR/thermal_prop.txt"
BACKUP_SWAPPINESS="$BACKUP_DIR/swappiness.txt"
BACKUP_ADRENOBOOST="$BACKUP_DIR/adrenoboost.txt"
BACKUP_WALT="$BACKUP_DIR/walt.txt"

LOG_FILE="$LOG_DIR/ther_t3.log"
CHANGE_LOG="$LOG_DIR/changes.log"

CAP_CPU_TOTAL=0
CAP_CPU_FREQ=0
CAP_CPU_PERF=0
CAP_CPU_SCHED=0
CAP_WALT="N/A"
CAP_GPU_CURRENT="N/A"
CAP_GPU_AVAIL="N/A"
CAP_GPU_PERF=0
CAP_GPU_PWRLEVEL="N/A"
CAP_GPU_NUM_LEVELS="N/A"
CAP_CORE_CTRL="N/A"
CAP_SCONFIG="N/A"
CAP_ZONES_TOTAL=0
CAP_ZONES_MODE=0
CAP_TRIP_TOTAL=0
CAP_TRIP_WRITABLE=0
CAP_TRIP_LOCKED=0

ACTIVE_PROFILE="None"
ACTIVE_GPU_PROFILE="None"

# WALT defaults per cluster (cpu0/cpu4/cpu7)
WALT_DEF_HISPEED_LOAD="90 85 85"
WALT_DEF_HISPEED_FREQ="1113600 1190400 1459200"
WALT_DEF_UP_RATE="0 0 0"
WALT_DEF_DOWN_RATE="0 0 0"
WALT_DEF_RTG_BOOST="595200 768000 0"
